repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
      - id: run-tests
        name: Run Pytest
        entry: python -m pytest --tb=short -q
        language: system
        pass_filenames: false
